package kolkova_tan;

//TIP To <b>Run</b> code, press <shortcut actionId="Run"/> or
// click the <icon src="AllIcons.Actions.Execute"/> icon in the gutter.
import java.util.List;

public class Main {
    public static void main(String[] args) {
        EmployeeDAO employeeDAO = new EmployeeDAO();

        System.out.println("=== Шаг 1: Добавление сотрудников ===");
        Employee emp1 = new Employee("Иван Петров", 28, "Junior Developer", 1200.0);
        Employee emp2 = new Employee("Анна Сидорова", 32, "QA Engineer", 1500.0);
        employeeDAO.addEmployee(emp1);
        employeeDAO.addEmployee(emp2);

        System.out.println("\n=== Шаг 2: Вывод всех сотрудников ===");
        printEmployees(employeeDAO);

        System.out.println("\n=== Шаг 3: Обновление сотрудника ===");
        // We retrieve all the data from the database to find out the current IDs generated by PostgreSQL
        List<Employee> currentList = employeeDAO.getAllEmployees();
        if (!currentList.isEmpty()) {
            Employee firstInDb = currentList.get(0);
            System.out.println("Оригинал из БД: " + firstInDb);

            // We change his position and salary
            Employee updatedVersion = new Employee(
                    firstInDb.getId(),
                    firstInDb.getName(),
                    firstInDb.getAge(),
                    "Middle Developer",
                    2200.0
            );
            employeeDAO.updateEmployee(updatedVersion);
        }

        System.out.println("\n=== Шаг 4: Вывод после обновления ===");
        printEmployees(employeeDAO);

        System.out.println("\n=== Шаг 5: Удаление второго сотрудника ===");
        if (currentList.size() > 1) {
            int idToDelete = currentList.get(1).getId();
            employeeDAO.deleteEmployee(idToDelete);
        }

        System.out.println("\n=== Шаг 6: Финальный список ===");
        printEmployees(employeeDAO);
    }

    private static void printEmployees(EmployeeDAO dao) {
        List<Employee> list = dao.getAllEmployees();
        if (list.isEmpty()) {
            System.out.println("В таблице нет записей.");
        } else {
            for (Employee e : list) {
                System.out.println(e);
            }
        }
    }
}